#database version mysql5.7; but use mysql8 driver; if boot failed;add a timezone in the url
spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/cbepis?useUnicode=true&characterEncoding=utf8
    driver-class-name: com.mysql.cj.jdbc.Driver

#shiro config path
shiro:
  anon-urls:
    - /toLogin*
    - /login.html*
    - /login/login
    - /login/getCode
    - /css/**
    - /echarts/**
    - /images/**
    - /layui/**
    - /layui_ext/**
    - /js/**
  login-url: /default.html
  log-out-url: /login/logout*
  authc--ulrs:
    - /**
